"""Add profile_image column

Revision ID: 6e653a607827
Revises: 
Create Date: 2025-05-21 18:14:20.289946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e653a607827'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
  
    op.add_column('users', sa.Column('profile_image', sa.String(length=128), nullable=True))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.create_index('detail', 'assignments', ['detail'], unique=True)
    op.create_table('all_courses',
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('courseID', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('semester', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('college', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('level', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('courseID', 'all_courses', ['courseID'], unique=True)
    # ### end Alembic commands ###
